general.import = [ "~/.config/alacritty/colors.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }
size = 12.0

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

