[colors.primary]
background = '#0e1416'
foreground = '#dee3e5'

[font]
normal = { family = "IBM Plex Sans"}
bold = { family = "Zed Sans", style = "Bold" }
italic = { family = "Zed Sans", style = "Medium Italic" }
size = 11 
 
